name: real_estate_task

description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter_riverpod: ^2.1.1
  riverpod_infinite_scroll: ^1.0.9
  infinite_scroll_pagination: ^3.2.0
  cached_network_image: ^3.2.3
  json_annotation: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed: ^2.1.0+1
  json_serializable: ^6.5.4
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true